# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 203caa02a5a2d04d6e1148d90d65c648965baebc5f4b5c7b5d632fc647a222cfd0354b2e4e9369cfe0e084cdb4129a7836e0fc02f64c99939037674f64567954

test:
  secret_key_base: 3732bfe8aa679016d04f645b7fc4118e4d16493ffc6d479217ab95aff4a8ce9f622118bc21c2776d35308f206d4cd7cae1d83c09c25555216cbc78a50602e87d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
