# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfe7f04d3a8ddf879c76a3dcadd39ab3ca7d17edb38ae009e7f4035f8fdd56c6d1723bff48f57c28744f9d1ce87fba16a51bf94fe6933c51c34b19cc41530bc7

test:
  secret_key_base: dcb54322e03a89e966b1963c6f0148a8c4e2781ccc3f0f5a06333192911a8ac10b5a2d6078aeb77475a4166f81b5e007c5e03b69e51528341da3c87ffa3bc518

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
