# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eac7f935e0dcd0f002d61184a81dbb7bc97246ca1d8c4f6b0133db0bb64eb1643cca1162ff78fb31ef35db6b82f97fe15f3a6e4ce6b0ed808435bb5f2f63f7c

test:
  secret_key_base: 178571b4de6f37278385108214bdcd8f098bf23b5112ad196c42a21656683313ba66c6b17bfe3684ab1eee27ea25d4315a0a251faf6e0f32dd7ab6b23a45b7cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
