# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bed1bf1430765ae037ba95d1287e6e97129a3d4acb60968137b8c326cae9f9f8acbdf404c74b8d98be6fb54aee32455a6a63b5e82fea636213d82adc3923acb1

test:
  secret_key_base: 18ccec32c094b97bbeb25997359589de3a880230ba325aa1a9738b6d285a4fb98c921dbd178da8493901a6a195ad711adbf3debfe17f9998f9206b66371c5ed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
