# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0669c6cd3ec9e4f1400ed89ae4555233c8240b0a027091ebef6cacf0e4d752113c230a97803bf01ded68af880209460304a94e270eef616a6c83b45ea10bd956

test:
  secret_key_base: 3b3bf5083c7a1c87e0d0f30867af89e28e1e3d3345cce1c3a395ae285622345ff6a6351125f0ab7ca6f966543a2c2c52ac042073a9fb961d51307beccfe5e8b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
