# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e59adaf081846a8f54f71c25d2bb3e37311d2e1f0d7a6548ed24026983d8efb0247bed3b665940a2d541da45622517dc33462403b26113418103e96637b2f47

test:
  secret_key_base: 52d4980e5127f30054b1415af387eaa583a094abdf8d1098204f8952d261c1e715e680385b259b15d1c2c6f30f070097fea6babe5329d8c8013f254969f00229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
